Main E2E
google-developer-training/basic-android-kotlin-compose-training-sports pull request #13
Opened 2023-08-11 21:49 UTC by android-dev-lxl

2023-08-14 06:54 UTC, johnshea requested changes
Navigation bar is not translucent and it should be.
<img width="814" alt="Screenshot 2023-08-14 at 9 50 04 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-sports/assets/7107817/97113c27-6b0b-4963-8363-e0f4c8a136b6">

Update gradle wrapper to `8.2`

2023-08-14 06:54 UTC, johnshea commented on app/src/main/java/com/example/sports/ui/theme/Theme.kt
> +}
Add newline at EOF.

2023-08-14 06:54 UTC, johnshea commented on app/build.gradle.kts
Upgrade BOM to `2023.08.00`.

2023-08-16 23:17 UTC, johnshea requested changes
UI does not have translucent navigation bar on lower APIs but it should.

Update gradle wrapper to `8.2`


<img width="764" alt="Screenshot 2023-08-17 at 2 06 30 AM" src="https://github.com/google-developer-training/basic-android-kotlin-compose-training-sports/assets/7107817/aeefccfe-ce5e-40ab-a341-9fc6e28fe602">

2023-08-18 19:11 UTC, android-dev-lxl commented
> UI does not have translucent navigation bar on lower APIs but it should.
> 
> Update gradle wrapper to `8.2`
> 
> <img alt="Screenshot 2023-08-17 at 2 06 30 AM" width="764" src="https://user-images.githubusercontent.com/7107817/261156909-aeefccfe-ce5e-40ab-a341-9fc6e28fe602.png">

Navbar is translucent, it is just the padding that you are noticing.

2023-08-21 15:05 UTC, johnshea approved these changes
LGTM with small changes.

- Update gradle wrapper to `8.2`
- Remove commented out code

2023-08-21 15:05 UTC, johnshea commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +        //val activity = (LocalContext.current as Activity)
Remove commented out code.

2023-09-15 01:10 UTC, merged