Versions update
google-developer-training/basic-android-kotlin-compose-training-sports pull request #2
Opened 2022-10-31 23:24 UTC by osuleymanova

Updated:
Kotlin, compose, material3 versions
AGP and Gradle versions
libraries number versions

2022-11-02 08:11 UTC, angiesasmita approved these changes

2022-11-02 08:21 UTC, angiesasmita requested changes
Also change `tools:targetApi` to `33` in AndroidManifest.xml

2022-11-02 16:43 UTC, osuleymanova commented
> Also change `tools:targetApi` to `33` in AndroidManifest.xml

Done!

2022-11-03 00:48 UTC, angiesasmita approved these changes

2022-11-15 23:00 UTC, merged