M3 UI redesign
google-developer-training/basic-android-kotlin-compose-training-sports pull request #7
Opened 2023-03-24 22:09 UTC by OwenScott-GDS

2023-03-28 18:39 UTC, android-dev-lxl requested changes

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/androidTest/java/com/example/sports/ExampleInstrumentedTest.kt
> + *
Do we need this file?

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/ui/theme/Color.kt
> +val seed = Color(0xFF1C520A)
We can delete this unused color

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/ui/theme/Color.kt
> +val md_theme_light_shadow = Color(0xFF000000)
Are we using this resource?
I think we can delete these resources, since we are not using. 
md_theme_light_shadow
md_theme_dark_shadow

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/ui/theme/Theme.kt
> +package com.example.sports.ui
Fix the package name `com.example.sports.ui.theme`
So you don't have to import all the colors, they are from the same package.

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/ui/theme/Theme.kt
> +import com.example.sports.ui.theme.md_theme_light_tertiaryContainer
This can be optimized once you change the package name.

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/ui/theme/Theme.kt
> +  }
Please use M3 template code here.
```

fun SportsTheme(
    darkTheme: Boolean = isSystemInDarkTheme(),
    // Dynamic color is available on Android 12+
    dynamicColor: Boolean = true,
    content: @Composable () -> Unit
) {
    val colorScheme = when {
        dynamicColor && Build.VERSION.SDK_INT >= Build.VERSION_CODES.S -> {
            val context = LocalContext.current
            if (darkTheme) dynamicDarkColorScheme(context) else dynamicLightColorScheme(context)
        }

        darkTheme -> DarkColorScheme
        else -> LightColorScheme
    }
    val view = LocalView.current
    if (!view.isInEditMode) {
        SideEffect {
            val window = (view.context as Activity).window
            window.statusBarColor = colorScheme.primary.toArgb()
            WindowCompat.getInsetsController(window, view).isAppearanceLightStatusBars = darkTheme
        }
    }
```

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/ui/theme/Theme.kt
> +private val LightColors = lightColorScheme(
Let's keep using `LightColorScheme` and `DarkColorScheme`

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/ui/theme/Theme.kt
> +  MaterialTheme(
Add Typography.
And use `colorScheme`

```
       colorScheme = colorScheme,
        typography = Typography,
        content = content
```

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/ui/theme/Type.kt
> + * Copyright (C) 2023 The Android Open Source Project
Nit: did you add or delete space here.

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/res/values/colors.xml
>  <resources>
Delete this file completely, you will set the status bar color in themes, if you use M3 template.

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/main/res/values/themes.xml
> +        <item name="android:windowTranslucentStatus">true</item>
This needs to be done in Themes.xml

2023-03-28 18:39 UTC, android-dev-lxl commented on app/src/test/java/com/example/sports/ExampleUnitTest.kt
> +}
Could we remove this file.

2023-03-28 19:09 UTC, johnshea commented on app/build.gradle
> +    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:$lifecycle_version"
Not in the correct spot alphabetically.

2023-03-28 19:09 UTC, johnshea commented on app/src/main/res/values/dimens.xml
> +</resources>
Ending blank line is missing.

2023-03-28 19:09 UTC, johnshea commented on app/src/androidTest/java/com/example/sports/ExampleInstrumentedTest.kt
> +}
Ending blank line is missing.

2023-03-28 20:13 UTC, android-dev-lxl requested changes

2023-03-28 20:13 UTC, android-dev-lxl commented on app/src/main/java/com/example/sports/MainActivity.kt
>          setContent {
Surface missing from the template.

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +    modifier: Modifier = Modifier,
no modifier on the main composable

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +                modifier = modifier.padding((innerPadding))
modifier = Modifier

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +                    modifier = modifier.padding((innerPadding))
modifier = Modifier

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +                    modifier = modifier.padding((innerPadding)),
modifier = Modifier

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +//                    modifier = Modifier.
remove comment

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +            .size(dimensionResource(R.dimen.card_image_height))
have this passed in from the parent

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +
dont need these parentheses for Column if theres nothing in there

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/java/com/example/sports/ui/SportsScreens.kt
> +        modifier = modifier.fillMaxWidth()
pass in fillMaxWidth from the parent

2023-03-29 22:04 UTC, MagicalMeghan commented on app/src/main/res/values/themes.xml
> +        <item name="android:windowTranslucentStatus">true</item>
+1

2023-04-03 17:08 UTC, MagicalMeghan approved these changes

2023-04-03 19:21 UTC, jhansitavva approved these changes

2023-04-03 19:22 UTC, android-dev-lxl commented on app/src/main/res/values/dimens.xml
> +    <dimen name="topappbar_height">64.dp</dimen>
64dp
Follow same convention.

2023-04-27 17:03 UTC, merged